spring.application.name=tictactoe

spring.cassandra.keyspace-name=${CASSANDRA_KEYSPACE:tictactoe}
spring.cassandra.contact-points=${CASSANDRA_CONTACT_POINTS:127.0.0.1}
spring.cassandra.port=${CASSANDRA_PORT:9042}
spring.cassandra.local-datacenter=${CASSANDRA_LOCAL_DATACENTER:datacenter1}
